services:
  ros:
    build: .
    user: ${USER_ID:-1000}:${GROUP_ID:-1000}
    volumes:
      - ${PROJECT_DIR}:/workspace/${PROJECT_BASENAME:-project}
    network_mode: host
    tty: true
    stdin_open: true
    command: bash
